### DISCUSSION TITLE
how to change array value

### DISCUSSION THREAD

**Discussion by billow-dev** [spf13/viper#1223] [Q&A]
base: app.toml

```toml
[[A]]
ID=1
[[A]]
ID=2
```
i want this:
```toml
[[A]]
ID=999
[[A]]
ID=2
```

I have try to use `Set`，but don't worker, who can help me?
