### DISCUSSION TITLE
How to override config file?

### DISCUSSION THREAD

**Discussion by bhojport** [spf13/viper#1272] [Q&A]
I'm just exploring the viper. And curious to know if we can override the config from a file?
```
#foo.yml
DB:
  HOST: "localhost"
  PORT: "80"

#bar.yml
DB:
  HOST: "site.com"
```

So that I can get:
```
DB:
  HOST: "site.com"
  PORT: "80"
```

I have read everything but I couldn't find a way to override the config file. Isn't it possible?
