### DISCUSSION TITLE
how to parse complex nested config struct for docker environment?

### DISCUSSION THREAD

**Discussion by TianTianBigWang** [spf13/viper#1345] [Q&A]
I have a config file, like this:
```
logger:
  level: debug
endpoints:
  - metadata:
      name: ""
      kind: email
    target:
      user:
        name: userA
        age: 18
  - metadata:
      name: ""
      kind: email
    target:
      user:
        name: userB
        age: 20
```

So, how can I set the ENV ,that viper can parse it correctly.

The ENV format like `MYPREFIX_LOGGER_LEVEL=debug`.

Thank you to everyone who can help me.
