### DISCUSSION TITLE
How to GetStringMapStringSlice from environment variable?

### DISCUSSION THREAD

**Discussion by timurbabs** [spf13/viper#1390] [Q&A]
Hi!
Have a probplem with getting map of string slices from environment variable.
I know how to get list of strings from environment variable:
```shell
SOME_EXAMPLE="TEST1 TEST2"
```

But how can I describe map of string slices as environment variable?
For example in .yml:
```yaml
map:
  key1:
    - value1
    - value2
  key2:
    - value1
    - value2
```
