### DISCUSSION TITLE
Loading Kubernetes environment variables

### DISCUSSION THREAD

**Discussion by pejeio** [spf13/viper#1520] [Q&A]
I'm trying to load the environment variables defined in my Kubernetes yaml file like this:
```go
type Config struct {
	AppClientId     string `mapstructure:"APP_CLIENT_ID"`
	AppClientSecret string `mapstructure:"APP_CLIENT_SECRET"`
	AppUserId       string `mapstructure:"APP_USER_ID"`
}

func LoadConfig() (config Config, err error) {
	viper.AutomaticEnv()
        err = viper.Unmarshal(&config)
        viper.GetViper().Debug()
	return
}
```

**Kubernetes yaml file**
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        imagePullPolicy: Never
        image: docker.io/library/the-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: APP_USER_ID
          value: "006692149"
        - name: APP_CLIENT_ID
          value: "01c7cd4c94ca4b42bd3bf21dd460d273"
        - name: APP_CLIENT_SECRET
          value: "49d97953d9ed4b41b1baf75502dc47e2"
```

Unfortunately,  the environment variables are not loading:
```
Aliases:                                                                                                               │
│ map[string]string{}                                                                                                    │
│ Override:                                                                                                              │
│ map[string]interface {}{}                                                                                              │
│ PFlags:                                                                                                                │
│ map[string]viper.FlagValue{}                                                                                           │
│ Env:                                                                                                                   │
│ map[string][]string{}                                                                                                  │
│ Key/Value Store:                                                                                                       │
│ map[string]interface {}{}                                                                                              │
│ Config:                                                                                                                │
│ map[string]interface {}{}                                                                                              │
│ Defaults:                                                                                                              │
│ map[string]interface {}{}                                                                                              │
│ {  }
```
