### DISCUSSION TITLE
I'm looking for a way to get the a map of keys for the root in a yaml file.

### DISCUSSION THREAD

**Discussion by xqa** [spf13/viper#1527] [Q&A]
I'm looking for a way to get the a map of keys for the root in a yaml file.

like `viper.RootKey()` Would return key1、key2、key3.

I know `viper.AllKeys()`, this returns key1.subkey1, key1.subkey2, key2.subkey3 ... , this is not the result I want.

Has anyone done this?

```
key1:
  subkey1:
  subkey2:
key2:
  subkey3:
  subkey4:
key3:
  subkey5:
  subkey6:
```
