### DISCUSSION TITLE
Binding slices of maps and flags

### DISCUSSION THREAD

**Discussion by hacel** [spf13/viper#1569] [Q&A]
So I have this config file:

```yaml
people:
  - name: john
    age: 24
  - name: james
    age: 25
  - name: johnson
    age: 26
```

I can easily access this in code with `people.0.name` for example. I can even access this in env vars if I do `cfg.SetEnvKeyReplacer(strings.NewReplacer(".", "_"))` and then set `PEOPLE_0_NAME=jason`.
But how do I bind a flag to it? I imagine this would be something like `--people.0.name jerome` and `--people.0.age 22` but I'm not sure if pflag supports this.
