### DISCUSSION TITLE
How to parse and get array of objects?

### DISCUSSION THREAD

**Discussion by howarddo2208** [spf13/viper#1579] [Q&A]
suppose I have `config.yaml` like this:
``` yaml
jobs: 
  test1:
    cmd: cd ~/Downloads && pwd
    schedule: "*/2 * * * * *"
  test2:
    cmd: cd ~/Sync/howard-pkm && pwd
    schedule: "*/3 * * * * *"
  test3:
    cmdFile: ./test-data/test-script.sh
    schedule: "*/4 * * * * *"
```
and a struct `Job` (optional cmd or cmdFile)
```
type Job struct {
	cmd      string
	cmdFile  string
	schedule string
}
```
How do I parse my yaml file to get the `[]Job`? Thank you for your help! I got stuck for multiple hours on this.
