### DISCUSSION TITLE
How to avoid writing unnecessary objects into TOML with WriteConfig

### DISCUSSION THREAD

**Discussion by instructorUz** [spf13/viper#1596] [Q&A]
I'm using Viper to read, modify and then write TOML configuration. The issue I have is how Viper handles the configuration structure when writing to TOML file. 

My initial config.toml looks like this:

```TOML
[plugins."io.containerd.nri.v1.nri"]
disable = true
disable_connections = true
```

and I would like to modify it to be like this
```TOML
[plugins."io.containerd.nri.v1.nri"]
disable = false
disable_connections = true
```

The go code I'm using:
```go
package main

import (
	"fmt"

	"github.com/spf13/viper"
)

func main() {
	viper.SetConfigName("config")
	viper.SetConfigType("toml")
	viper.AddConfigPath("/path")
	viper.ReadInConfig()

	viper.Set("plugins.io.containerd.nri.v1.nri.disable", false)

	err := viper.WriteConfigAs("/path/config.toml")
	if err != nil {
		fmt.Printf("Error writing config file, %s", err)
	} else {
		fmt.Println("Configuration updated successfully")
	}
}
```
However, when Viper writes into the config.toml I'm getting unnecessary entry names of all the nested fields.

```TOML
[plugins]       #unnecessary
[plugins.io]   #unnecessary
[plugins.io.containerd]   #unnecessary
[plugins.io.containerd.nri]   #unnecessary
[plugins.io.containerd.nri.v1]   #unnecessary
[plugins.io.containerd.nri.v1.nri]
disable = false
disable_connections = true
```
Is there a way to avoid those extra objects ?
