### DISCUSSION TITLE
How to bind environment variables to a yaml list of dictionaries

### DISCUSSION THREAD

**Discussion by yohanleb** [spf13/viper#1933] [Q&A] [answered]
Hello,

I am trying to override this yaml struct with environment variables.
```
auth:
  providers:
    - google:
        name: Google
        client_id: <CHANGE_ME>
        client_secret: <CHANGE_ME>
        issuer: https://accounts.google.com
    - provider:
        name: Provider
        client_id: <CHANGE_ME>
        client_secret: <CHANGE_ME>
        issuer: <CHANGE_ME>
```

I made this function to bind each AUTH_PROVIDERS_{NAME}_{KEY} env variable to the corresponding dict in the yaml struct.
```
keys := []string{"name", "client_id", "client_secret", "issuer"}
providers := strings.Split(v.GetString("AUTH_PROVIDERS"), ",")
for _, provider := range providers {
    providerUpper := strings.ToUpper(provider)
    for _, key := range keys {
	    keyUpper := strings.ToUpper(key)
	    _ = v.BindEnv(
		    fmt.Sprintf("auth.providers.%s.%s", provider, key),
		    fmt.Sprintf("AUTH_PROVIDERS_%s_%s", providerUpper, keyUpper),
	    )
    }
}
```

This is my environment:
```
AUTH_PROVIDERS=google
AUTH_PROVIDERS_GOOGLE_NAME=Google
AUTH_PROVIDERS_GOOGLE_CLIENT_ID=custom_client_id
AUTH_PROVIDERS_GOOGLE_CLIENT_SECRET=custom_client_secret
AUTH_PROVIDERS_GOOGLE_ISSUER=https://accounts.google.com
```

However, the result is not what I expected. Sometimes it works and all the variables are set properly, sometimes only the client_id, sometimes only the client_secret, sometimes none of them, etc...

How can I achieve that ?
I went through stackoverflow and the Viper issues and I couldn't find a similar discussion with a satisfying solution. I'm currently learning Go and coming from a Python background so any feedback is welcome.

Thank you !
