### ISSUE TITLE
UnmarshalKey: Using "y" variable in yml stays empty

### ISSUE THREAD

**Issue by maltegrosse** [spf13/viper#1146]
**Expected behavior (what you expected to happen)**:
By using a yaml file with an array and 3 fields, e.g.
```
---
genres:
  - genre: soul
    x: 703
    y: 15128
  - genre: pop
    x: 1150
    y: 13682
```

and creating a struct 
```
type Genre struct {
	Genre string `mapstructure:"genre"`
	Y int `mapstructure:"y"`
	X int `mapstructure:"x"`

}
var Genres []Genre
```
```
viper.UnmarshalKey("genres", &Genres)
```

should fill the structs with string genre,int x and y.

**Actual behavior (what actually happened)**:
Field Y stays empty. X is filled with a value.

Workaround:

Rename yaml field to any other variable, e.g. ```mm``` and use in struct: ```Y int `mapstructure:"mm"` ```

**Environment**:
- Viper version: v1.7.1
- Config source: file
- File format: YAML

**Comment by xwjdsh** [comment]
https://github.com/go-yaml/yaml/issues/740
In YAML 1.1, scalars like y and Y are resolved as booleans, change to this,
```
---
genres:
  - genre: soul
    x: 703
    'y': 15128
  - genre: pop
    x: 1150
    'y': 13682
```
