### ISSUE TITLE
`SetDefault` doesn't work as expected

### ISSUE THREAD

**Issue by ashep** [spf13/viper#1153]
Suppose we have following YAML config:

```yaml
logging:
  file:
    path: log/$SERVICE_NAME.log
    age: 30
    backups: 10
```

and following code:

```go
cfg := viper.New()
cfg.SetDefault("logging.file.size", 100)

if err := vp.ReadInConfig(); err != nil {
    if _, ok := err.(viper.ConfigFileNotFoundError); !ok {
	return nil, err
    }
}
```

Then after executing following:

```go
fmt.Printf("size: %d\n", cfg.GetInt("logging.file.size"))
```

it is expected to get

```
100
```

but instead we'll see:

```
0
```
