### ISSUE TITLE
Add a .SetConfigPrefix(string) method

### ISSUE THREAD

**Issue by code-n-go** [spf13/viper#1313]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/spf13/viper/issues) for an issue that matches the one I want to file, without success.

### Problem Description

Right now, we group our environment variables by service name... prepending them to such (e.g. ANALYTICS_ENV, etc.).  Currently, using .SetEnvPrefix("analytics"), we can reference everything in-app just by using .GetString("env").  Perfect.  Now, let's say we have a config file that we want to group such by service name also:

``` yaml
 analytics:
   host: 127.0.0.1
   port: 8080
   versions:
     - v1
     - v2
```

It would still be great to reference those by a prefixed key also, just like the environment variables.

### Proposed Solution

Include a .SetConfigPrefix(string) method that allows config files to be categorized by key, and able to retrieve those values w/o referencing it with every Get call.  E.g.:

``` yaml
 analytics:
   host: 127.0.0.1
   port: 8080
   versions:
     - v1
     - v2
```

``` go
   viper.SetConfigPrefix("analytics")
   
   _ := viper.GetStringSlice("versions")
```
