### ISSUE TITLE
Enable Get/Sub of Array (not just map)

### ISSUE THREAD

**Issue by ykoehler** [spf13/viper#1314]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/spf13/viper/issues) for an issue that matches the one I want to file, without success.

### Problem Description

Given the yaml file

```
tree:
  fruits:
    - name: apple
      other: style1
    - name: orange
      other: style2
    - name: citrus
      other: style3
```

I would like to be able to do

```
type Fruit struct {
  name string
  other string
}

var fruits []Fruit
fruits_config = viper.Sub("tree.fruits")
fruits_config.Unmarshal(&fruits)
```

Yet, the source code seems to only work if the "fruits" is a map, when it is an array, Get/Sub returns nil.

### Proposed Solution

Handle Map but also Array under viper.Get/Sub for yaml support
