### ISSUE TITLE
Config Builder

### ISSUE THREAD

**Issue by soheilrt** [spf13/viper#1347]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/spf13/viper/issues) for an issue that matches the one I want to file, without success.

### Problem Description

When a developer uses Viper as config manager inside a Go application, the easiest way is to pass Viper instance everywhere and fetch config information through Viper instance. The way of using Viper instance adds the following issues to the project.

- It adds an extra dependency to code, and it gets hard to use any other config providers in case of necessity. 

- It’s always a possibility of a typo when a user wants to request a config from Viper due to string format input (e.g: DtaBase instead of Database). It’s worth saying that typo issues can be solved easily by defining constant variables and using them, but still is a problem.
- Sometimes developers want to add a validation to a few configs to make sure that entered values in a config file are as expected. This way, the number of investigations because of the bad or missing values will reduce, but the current structure of the Viper does not provide this future and user has to implement it manually. This issue gets worse when the value needs to be used in different places.

### Proposed Solution

Usually in go applications, if developer wants to isolate the config provider from the application point of view, the person creates a global struct and uses the struct in the application. The general config provider could be something like this:

```go
type Config struct {
   DataBase struct {
	 Host string
	 Port uint
	 Username string
	 ...
   }
  ...
}

```
The difficulty with the above config struct is that there is always some maintenance applied to this file to keep it up to date or requires some extra effort to write validation rules for variables.

## Solution
If there is a tool to generate a Config struct and related codes for validation and other required codes, lots of the concerns will fade away since lots of the maintenance for managing config instance will handle automatically. 

There is one downside to achieving this goal worth mentioning, and that would be developer might need to write down an extra configuration file for generating this config. The many basic config file that might be required by the generator could be something like below:

```yaml
Config:
 sources: 
   File: 
     type: "file"
     path: "config.yaml"
     Hotreload: true
   Env:  
     type: "environment"

  Code:
    Path: "./pkg/config"
    package: "config"

  Definitions:
    Database:
      Url:
       source: "file"
       Key: "database.url"
       Type: "string"
       Validation: "required,url"
       Fallbacks:
        - source: "env"
          key: "DATABASE_URL"
     Username: 
       Type: "string"
       Validation: "required"
      Port: 
       Type: "int"
       Default: 5432
  ...
```

### Additional Information

I really need this future and I really like to work on it, but I don’t know if it’s a good idea to add this future to the core of the Viper. 

PS: this Narrative is in its very first version, and it can be improved in many areas. I very much welcome anyone’s advice regarding improving the quality of this narrative.
