### ISSUE TITLE
Is there any plan to add environment variable support for YML，like springboot application.yml ?

### ISSUE THREAD

**Issue by seepine** [spf13/viper#1415]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/spf13/viper/issues) for an issue that matches the one I want to file, without success.

### Problem Description

it is easy to use  viper read yml config, but some config unsuited write file, so this is necessary of add environment variable support for YML, like springboot `application.yml` support system environment

### Proposed Solution

for example, at the time of development, There is no environment variable; it will use the default value like `127.0.0.1`、`root`、`123456`
when the environment variable exists, it will preferentially use the environment variable
```yml
datasource:
  host: ${MYSQL_HOST:127.0.0.1}
  port: 3306
  database: test
  username: ${MYSQL_USER:root}
  password: ${MYSQL_PASSWORD:123456}
```
