### ISSUE TITLE
remote Unmarshal YAML to structure

### ISSUE THREAD

**Issue by Moranilt** [spf13/viper#1535]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/spf13/viper/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/spf13/viper/issues/new/choose) without success.
- [X] I have checked the [troubleshooting guide](https://github.com/spf13/viper/blob/master/TROUBLESHOOTING.md) for my problem, without success.

### Viper Version

1.15

### Go Version

1.20

### Config Source

Remove K/V stores

### Format

YAML

### Code reproducing the issue

```go
package main

import (
	"github.com/spf13/viper"
	_ "github.com/spf13/viper/remote"
	"gopkg.in/yaml.v2"
)

type Config struct {
	Hosts []Host `yaml:"hosts"`
}

type Host struct {
	Hostname  string     `yaml:"hostname"`
	Prefix    string     `yaml:"prefix"`
	Endpoints []Endpoint `yaml:"endpoints"`
}

type Endpoint struct {
	Pattern         string   `yaml:"pattern"`
	Methods         []string `yaml:"methods"`
	MwToken         bool     `yaml:"mw_token"`
	Authentication  bool     `yaml:"authentication"`
	Roles           []int    `yaml:"roles"`
	HeadersRequired []string `yaml:"headers_required"`
}

func ReadConsulConfig(host, key string) (*Config, error) {
	err := viper.AddRemoteProvider("consul", host, key)
	if err != nil {
		return nil, err
	}

	viper.SetConfigType("yaml")
	err = viper.ReadRemoteConfig()
	if err != nil {
		return nil, err
	}
	
	cfg := new(Config)
	err = viper.Unmarshal(cfg)
	if err != nil {
		return nil, err
	}
	
	return cfg, nil
}

func main() {
	cfg, err := ReadConsulConfig("localhost:8500", "test/config.yaml")
	if err != nil {
		log.Fatal(err)
	}

	fmt.Printf("%#v", cfg)
}
```

### Expected Behavior

Expected to get structure:
```yaml
hosts:
  - hostname: http://localhost:1111
    prefix: /test
    endpoints:
      - pattern: /subroute1
        mw_token: true
        methods: [GET, DELETE]
      - pattern: /subroute2
        mw_token: true
        methods: [GET, PATCH]
```
Where `cfg.MwToken` should be **true**

### Actual Behavior

```yaml
hosts:
  - hostname: http://localhost:1111
    prefix: /test
    endpoints:
      - pattern: /subroute1
        mw_token: false
        methods: [GET, DELETE]
      - pattern: /subroute2
        mw_token: false
        methods: [GET, PATCH]
```

Where `cfg.MwToken` is **false**

### Steps To Reproduce

1. Docker compose file:
```yaml
services:
  consul:
    image: consul
    ports:
      - "8300:8300"
      - "8500:8500"
      - "8600:8600/udp"
    networks:
      - consul_init
  
  consul_init:
    image: consul
    restart: on-failure
    entrypoint: >
     sh -c "consul kv put -http-addr=http://consul:8500 test/config.yaml @/configs/config.yaml"
    volumes:
      - ./config.yml:/configs/config.yaml
    depends_on:
      - consul
    networks:
      - consul_init
```
2. Config file `config.yaml`:
```yaml
hosts:
  - hostname: http://localhost:1111
    prefix: /test
    endpoints:
      - pattern: /subroute1
        mw_token: true
        methods: [GET, DELETE]
      - pattern: /subroute2
        mw_token: true
        methods: [GET, PATCH]
```
3. Run `docker compose up -d`
4. File `main.go`. Run code:
```go
package main

import (
	"github.com/spf13/viper"
	_ "github.com/spf13/viper/remote"
)

type Config struct {
	Hosts []Host `yaml:"hosts"`
}

type Host struct {
	Hostname  string     `yaml:"hostname"`
	Prefix    string     `yaml:"prefix"`
	Endpoints []Endpoint `yaml:"endpoints"`
}

type Endpoint struct {
	Pattern         string   `yaml:"pattern"`
	Methods         []string `yaml:"methods"`
	MwToken         bool     `yaml:"mw_token"`
	Authentication  bool     `yaml:"authentication"`
	Roles           []int    `yaml:"roles"`
	HeadersRequired []string `yaml:"headers_required"`
}

func ReadConsulConfig(host, key string) (*Config, error) {
	err := viper.AddRemoteProvider("consul", host, key)
	if err != nil {
		return nil, err
	}

	viper.SetConfigType("yaml")
	err = viper.ReadRemoteConfig()
	if err != nil {
		return nil, err
	}
	
	cfg := new(Config)
	err = viper.Unmarshal(cfg)
	if err != nil {
		return nil, err
	}
	
	return cfg, nil
}

func main() {
	cfg, err := ReadConsulConfig("localhost:8500", "test/config.yaml")
	if err != nil {
		log.Fatal(err)
	}

	fmt.Printf("%#v", cfg)
}
```

### Additional Information

It works fine if you provide tag to `MwToken` field as `mapstructure:"mw_token"`, but it's not obvious, when you are running `viper.SetConfigType("yaml")` and it doesn't use `yaml` tags to parse config. So it doesn't metter to run `viper.SetConfigType("yaml")` as shown in your documentation https://github.com/spf13/viper#consul because it's not using tags of selected config type which does not make sense.

```go
type Endpoint struct {
	Pattern         string   `yaml:"pattern"`
	Methods         []string `yaml:"methods"`
	MwToken         bool     `mapstructure:"mw_token"`
	Authentication  bool     `yaml:"authentication"`
	Roles           []int    `yaml:"roles"`
	HeadersRequired []string `yaml:"headers_required"`
}
```

It would be better to use tags of selected config type, instead of mupstructure. I think it's more obvious.
