### ISSUE TITLE
Panic when using a .Sub extraction with capitalized yaml

### ISSUE THREAD

**Issue by tony** [spf13/viper#167]
Greetings viper devs, I'm still on my first few days of golang, pardon any mistakes.

Edit: [Brief example you can run to try to re-create](https://github.com/spf13/viper/issues/167#issuecomment-193813223)

This panic happens if a capital letter is used as a key in YAML.

Code: https://github.com/tony/vcsync/blob/b1e810df1a2f01c127978be84be0c0fcf6d3c938/main.go. I'm working on creating a more brief example.

The funky thing is that I'm parsing the rest of [this whole file](https://github.com/tony/.dot-config/blob/439d58e4922b20bd83ac35a73690b59014874854/.vcspull.yaml), which uses very similar constructs fine.

I'll have a file `~/.vcspull.yaml`, here is the minimum config I need to recreate:

``` yaml
KeyA:
  KeyB: 
    KeyC:
      KeyD: 'string'
```

```
keya
map[KeyC:map[KeyD:string]]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0xa0 pc=0x47b3e2]

goroutine 1 [running]:
panic(0x8c3980, 0xc82000a130)
        /usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/spf13/viper.(*Viper).Sub(0xc820132540, 0xc82014302c, 0x4, 0x1b)
        /home/tony/work/go/src/github.com/spf13/viper/viper.go:529 +0x372
main.ExpandConfig(0xc820143174, 0x4, 0xc820198660, 0xc8201a9ec8, 0xc820132540)
        /home/tony/work/go/src/github.com/tony/vcsync/main.go:49 +0x2cc
main.main()
        /home/tony/work/go/src/github.com/tony/vcsync/main.go:21 +0x3c5
exit status 2
```

In practice, [this is whats failing](https://github.com/tony/.dot-config/blob/439d58e4922b20bd83ac35a73690b59014874854/.vcspull.yaml#L5):

``` yaml
~/study/data-structures-algorithms/c:
  libds: 'git+https://github.com/zhemao/libds.git'
  AlgoXY: 
    repo: 'git+https://github.com/liuxinyu95/AlgoXY.git'
    remotes:
      tony: 'git+ssh://git@github.com/tony/AlgoXY.git'
```

Gives:

```
~/study/data-structures-algorithms/c
map[remotes:map[tony:git+ssh://git@github.com/tony/AlgoXY.git]]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0xa0 pc=0x47b3e2]

goroutine 1 [running]:
panic(0x8c3980, 0xc82000a130)
        /usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/spf13/viper.(*Viper).Sub(0xc820132540, 0xc820143058, 0x6, 0x40)
        /home/tony/work/go/src/github.com/spf13/viper/viper.go:529 +0x372
main.ExpandConfig(0xc820196540, 0x24, 0xc8201966c0, 0xc8201a5ec8, 0xc820132540)
        /home/tony/work/go/src/github.com/tony/vcsync/main.go:49 +0x2cc
main.main()
        /home/tony/work/go/src/github.com/tony/vcsync/main.go:21 +0x3c5
exit status 2
```

You can minimize it to this and still get it:

``` yaml
~/study/data-structures-algorithms/c:
  AlgoXY: 
    remotes:
      tony: 'git+ssh://git@github.com/tony/AlgoXY.git'
```

Its something to do with https://github.com/spf13/viper/blob/c975dc1/viper.go#L529.

**Comment by tony** [comment]
Here's an even more minimal version:

```go
package main

import (
        "bytes"
        "fmt"

        "github.com/spf13/viper"
)

func main() {
        viper.SetConfigType("yaml") // or viper.SetConfigType("YAML")

        var yamlExample = []byte(`
KeyA:
        KeyB: 'hi'
`)

        viper.ReadConfig(bytes.NewBuffer(yamlExample))
        fmt.Println(viper.Sub("KeyA.KeyB"))
}
```

**Comment by tony** [comment]
```yaml
        var yamlExample = []byte(`
KeyA:
        KeyB: 'hi'
`)
```

returns a ``<nil>`` when using ``viper.Get("KeyA")``.

If it encounters a tab, no config will be be read. This may be a separate issue / already documented.
