### ISSUE TITLE
Can't get MarshallKey to work

### ISSUE THREAD

**Issue by blasphemy** [spf13/viper#23]
Hi, couldn't find an irc or something to discuss this on, so I'm posting it here.

I'm having trouble getting Marshall key to Unmarshal to a struct. Here's some example code of what I'm trying to do.

``` go

type Server struct {
  address string
  name string
}

var (
  ServerConfigs map[string]Server
)

func main() {
  ...
  viper.Marshalkey("servers", &ServerConfigs)
}
```

Example config in toml:

``` toml
[servers]
[servers.server1]
address = "serveraddress"
name = "server1"

[servers.server2]
address = "address2"
```

My result ends up being a map with the keys "server1" and "server2" with the struct fields being empty.

Any tips on getting this to work? Or is this something that requires #15 being implemented? I also can't find any documentation of using struct labels for the MarshalKey interface, is there any support for that?
