### ISSUE TITLE
Unmarshalling an array of structures with different layout

### ISSUE THREAD

**Issue by CountFenring** [spf13/viper#269]
Hi viper, 

We would like to unmarshal yaml file containing structures that share some fields but differ in some others, like the following yaml example :

```
conf:

    - commonField1: value
      commonField2: value
      ...
      AField1: value
      AField2: ...
 
    - commonField1: value
      commonField2: value
      ...
      BField1: value
      BField2: ...
```

This prevents us from using UnmarshalKey with an array of static structures as mapstructure won't load correctly this kind of structure.

We used a workaround provided by a fork of mapstructure : https://github.com/cbroglie/mapstructure
which solved this issue: https://github.com/mitchellh/mapstructure/pull/25

But this feature doesn't work anymore for us with the latest viper versions, because the latest mitchellh/mapstructure needed for viper isn't compatible with the fork.

What would be your advice to achieve this kind of unmarshalling ? 

We could fork mapstructure again, but we don't know if we're missing something in viper API.

Thanks in advance for your help
