### ISSUE TITLE
key auto lower?

### ISSUE THREAD

**Issue by elvizlai** [spf13/viper#293]
```yaml
ENV:
    REPO: git@github.com:xyz/abc.git
    WORKDIR: /gopath/src/github.com/xyz/abc
```

```go
type conf struct {
    ENV    map[string]string
}

```

Updating viper to newest, the key are all lower.(Previous version works well)
