### ISSUE TITLE
Unmarshaling of sequence of mappings doesn't work

### ISSUE THREAD

**Issue by kubaj** [spf13/viper#304]
Hi, unmarshaling sequence of mappings is not working for me. I have following yaml:
``` yaml
schedulers:
 - run: "echo \"hello owl\""
   path: .
 - run: "echo \"hello dir2\""
   path: ./.idea
time: 5000
verbose: true
ignore:
 - ".git"
 - "bin"
```
and structures:
``` golang
type Scheduler struct {
	Run string `yaml: "run"`
	Path string `yaml: "path"`
}

type Config struct {
	Schedulers []Scheduler `yaml: "schedulers"`
	Time int `yaml: "time"`
	Verbose bool `yaml: "verbose"`
	Ignore []string `yaml: "ignore"`
}
```
If I unmarshal config into the struct and print it using code below, I get `{[] 5000 true [.git bin]}` - everything is unmarshaled except sequence of mappings.
``` golang
conf := owl.Config{}
err = viper.Unmarshal(&conf)
if err != nil {
	fmt.Println(err.Error())
}
fmt.Println(conf)
```
If I print `viper.AllSettings()`, I get following:
```
map[verbose:true ignore:[.git bin] schedulers:[map[run:echo "hello owl" path:.] map[run:echo "hello dir2" path:./.idea]] time:5000]
```
So I think config is loaded and parsed properly by viper, but unmarshaling doesn't work. Is this issue or am I missing something somewhere? Thank you
