### ISSUE TITLE
Period in map key name not breaks when unmarshalling to struct

### ISSUE THREAD

**Issue by sevoma** [spf13/viper#348]
I'm unmarshalling yaml to a struct.
I've encountered issues unmarshalling if a map's key containers period character.

Struct that I unmarshall to:
```
type Config struct {
	ListenInterface string
	ListenPort      int
	Thing           map[string]SomeOtherThing
}

type SomeOtherThing struct {
	Stuff string
}
```

YAML:
```
ListenInterface: 127.0.0.1
ListenPort: 8080
Thing:
  .broken:
    Stuff: missing
  partially.works:
    Stuff: missing
  fully-works:
    Stuff: works
```

Output looks like:
```
(main.Config) {
 ListenInterface: (string) (len=9) "127.0.0.1",
 ListenPort: (int) 8080,
 Thing: (map[string]main.SomeOtherThing) (len=3) {
  (string) "": (main.SomeOtherThing) {
   Stuff: (string) ""
  },
  (string) (len=9) "partially": (main.SomeOtherThing) {
   Stuff: (string) ""
  },
  (string) (len=11) "fully-works": (main.SomeOtherThing) {
   Stuff: (string) (len=5) "works"
  }
 }
}
```
I put a demo here:
https://github.com/sevoma/testViper
