### ISSUE TITLE
Add environment variable prefix to yaml?

### ISSUE THREAD

**Issue by FX-HAO** [spf13/viper#365]
Let's say we this yaml:

```yaml
default: &default
  tls: false

development:
  port: 8000
  db: development

test:
  port: 8000
  db: test

production:
  tls: true
  port: 80
  db: production

```

It's common configuration in rails. 

```go
os.Setenv("GO_ENV", "production")
viper.SetEnvPrefix("GO_ENV")
viper.GetBool("tls")  // true
```

How to get this work?
