### ISSUE TITLE
Does viper support uppercase in yaml map?

### ISSUE THREAD

**Issue by Kvaz1r** [spf13/viper#371]
MCVE:
Yaml:
```
Test :
 Var1 : Hello
 Var2 : world
```
Code:
```
package main

import (
	"fmt"
	"log"

	"github.com/spf13/viper"
)

func main() {

	viper.SetConfigType("yaml")
	viper.SetConfigName("input")
	viper.AddConfigPath(".")
	if err := viper.ReadInConfig(); err != nil {
		log.Fatal(err)
	}
	fmt.Println(viper.GetStringMap("Test"))
}
```

Output:

> map[var1:Hello var2:world]

Epected output:

> map[Var1:Hello Var2:world]

That's bug or I do something wrong?

**Comment by benoitmasson** [comment]
Hi, this is the expected behavior, see #260 

In summary, viper configuration keys are case insensitive, and internally lowercased to enforce that.

What I do as a workaround when I really need case sensitivity of keys is the following:
```yaml
test:
    var1:
        contents: "Hello"
        key: "Var1"
    var2:
        contents: "world"
        key: "Var2"
```
but I agree this is not very convenient…
