### ISSUE TITLE
env var substitution inside config file

### ISSUE THREAD

**Issue by PepijnK** [spf13/viper#418]
Considering the following example YAML file excerpt:
```
---
version: 1
timeout: 3000ms
token_introspection_endpoint: ${DOWNSTREAM_SERVICES_URL}/auth/token
```

While reading the config, the value ${DOWNSTREAM_SERVICES_URL} should be replaced with env var  value of DOWNSTREAM_SERVICES_URL.

Is there some decoder hook I can use to implement this substitution?

**Comment by natemurthy** [comment]
I'm looking for a similar solution. My current application has config files that look like this:
```
database:
  host: $PG_HOST
  dbname: $PG_DBNAME
  username: $PG_USERNAME
  password: $PG_PASSWORD
```
and I would like to continue to use these configuration files as-is with the `viper` library. Do you have examples of using environment variable substitution?

**Comment by leandro-lugaresi** [comment]
This will help me to improve an application. I need some way to set the base URL for n HTTP consumers:
```yaml
    consumer-name-1:
      connection: default
      queue:
        name: "wololo"
        options:
          durable: true
      runner:
        type: http
        options:
          url: https://myurl/app/message/wololo-handler"
    consumer-name-2:
      connection: default
      queue:
        name: "fooo"
        options:
          durable: true
      runner:
        type: http
        options:
          url: https://myurl/app/message/fooo-handler"
```
I can help if needed!
