### ISSUE TITLE
Viper get on slice of maps?

### ISSUE THREAD

**Issue by josdotso** [spf13/viper#434]
I'm trying to range over something like `viper.Get("things")` (see below), and the result doesn't support ranging (program errors saying so when I try).

```
things:
  - name: this
    alias: that
    key: HelloThat
  - name: this
    alias: thatAgain
    key: HelloThatAgain
```

When I do `viper.Get("things")` I end up with something like the following, which seems to be a slice of maps, but still range doesn't work.  What am I doing wrong?

```
[map[alias:this key:HelloThat name:this] map[alias:thatAgain key:HelloThatAgain name:this]]
```

Thanks!
