### ISSUE TITLE
func InConfig does not work with composite keys foo.bar.xxx

### ISSUE THREAD

**Issue by peczenyj** [spf13/viper#447]
I have a config.yaml like this

```yaml
---
foo:
  bar:
     baz: 
       something: 1024
     bam: 
```

I want to check if foo.bar.bam exists in the configuration, even if the content is nil

I can't use `viper.IsSet("foo.bar.bam") ` -- of course this works fine for foo.bar.baz

I try `viper.InConfig("foo.bar.bam")` and it returns **false**.

but it works only for `InConfig("foo")` but not for a full composite key like foo.bar - this is by design ? why ?
