### ISSUE TITLE
Unmarshal laver2 []string failed

### ISSUE THREAD

**Issue by Omkaka09** [spf13/viper#491]
Hi, 
I have the following yaml.
```
p2p:
  timeout: 1
  list:
    - 127.0.0.1:37101
    - 127.0.0.1:37102

```
I try to use`Unmarshal` to load config to a struct, `list` not work, but `GetStringSlice` can load.
