### ISSUE TITLE
Viper incorrectly parses TOML

### ISSUE THREAD

**Issue by KaiserKarel** [spf13/viper#544]
I have a relatively simple configuration file:

 ```toml
configuration_id="SomeID"

# Logger configurations, autogenerated using GenerateLoggers
[logrus]

[[logrus.hooks]]
    name        = "airbrake"
    type        = "airbrake"
    project_id  = 1
    api_key     = ""
    environment = "local"
    backup = "sentry" # Name of the backup hook

[[logrus.hooks]]
    name    = "sentry"
    type    = "sentry"
    kind    = "default" # Options: default, async
    dns     = ""
    level   = "WARN" # Options: DEBUG, INFO, WARN, ERROR, CRITICAL

[[logrus.loggers]]
    name    = "api_logger"
    level   = "WARN"
    [[logrus.loggers.hooks]]
        name    = "airbrake"
[[logrus.loggers]]
    name    = "store_logger"
    level   = "WARN"
    [[logrus.loggers.hooks]]
        name    = "airbrake"


# Configurations for the API interface
[API]
    logger              = "api_logger"
    implementation      = "km_robin" # Options: km_robin
    buffer_size         = 10000
	error_buffer_size   = 10

[[API.providers]]
    logger              = "api_logger"

    exchange            = "binance"
    URL                 = "wss://stream.binance.com:9443/ws/"
    buffer_size         = 100
    error_buffer_size   = 10
    rate_limit          = 20 # max requests per second
    burst_limit         = 50 # max burst size

# Configurations for the STORE interface
[STORE]
    logger              = "store_logger"
    implementation      = "pg_robin" # options: pg_robin
    database_url        = "postgres://karel:wachtwoord@localhost/robin_test?sslmode=disable"
    sanity_policy       = "None" #  options: None, ClearConflictingBids, ClearConflictingAsks
    latency_service_RA  = 0
```

Using viper to parse this file into my configuration struct will result in all integers (buffersize, ratelimits etc) to be their nil values (0). Using https://github.com/BurntSushi/toml the file is correctly parsed.

Other values are parsed correctly.
