### ISSUE TITLE
Toml format doesn't work for me, what data format I should use  to parse ?

### ISSUE THREAD

**Issue by rossmeng** [spf13/viper#557]
Hi guys,
I have following data format configuration, I try to use toml format to parse, but it not work for that:
[myconf.txt](https://github.com/spf13/viper/files/2301010/myconf.txt)

the code complaint my key = value pair should be key = "string",  like domain=example.com should be domain="example.com" ,   and "timezone=" is not acceptable, too.

My question is what data format I should use to parse my configuration file like this?  Or viper not support this type of configuration file? 
I appreciate your feedback, thanks.

**Comment by zvodd** [comment]
See the language spec https://github.com/toml-lang/toml
``` TOML
# This is a TOML document.
title = "TOML Example"

[owner]
name = "Tom Preston-Werner"
dob = 1979-05-27T07:32:00-08:00 # First class dates

[database]
server = "192.168.1.1"
```

Your config file should look like this (comments redacted for readablity):
``` TOML
[general]
domain="example.com"
hostname = "a3"
dhcpservers = "127.0.0.1"
#timezone =
#not sure about this line, maybe it should be `timezone = ""` ?
```
