### ISSUE TITLE
how can i get this yaml list value?

### ISSUE THREAD

**Issue by r6c** [spf13/viper#615]
``` yaml
domains:
- domain: example.com
  ttl: 3600
  records:
    example.com:
      - soa: 
          content: ns.example.net hostmaster.example.net 20171005 7200 3600 86400 1800
          ttl: 3600
  services:
    www.example.com: [ '%ci.%cc.geo.example.com' ]
- domain: test.com
  ttl: 3600
  records:
    test.com:
      - soa: 
          content: ns.example.net hostmaster.example.net 20171005 7200 3600 86400 1800
          ttl: 3600
    www:
      - a:
          content: 127.8.2.1
          ttl: 600
    abc:
      - cname:
          content: 127.8.2.1
          ttl: 3600
  services:
    abc.test.com: [ 'unknown.%cn.geo.example.com' ]
```
like this, code `viper.AllKeys()` only show `doamins` key,how can i read `domain` value?
