### ISSUE TITLE
key case-sensitive

### ISSUE THREAD

**Issue by relax-admin** [spf13/viper#697]
Sometimes, the key is expected to be case-sensitive, such as an environment variable.Whether the viper can modify the case of the key？Such as the following `KAFKA_LISTENERS`

### exp

``` yml
  version: "3"
  kafka-server:
    environment:
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:29092
    image: wurstmeister/kafka
```

### act

```yml
  version: "3"
  kafka-server:
    environment:
      kafka_listeners: INSIDE://:9092,OUTSIDE://:29092
    image: wurstmeister/kafka
```

### sample
>    https://github.com/relax-space/test-viper

```golang
package main

import (
	"fmt"
	"os"
	"strings"

	"github.com/ghodss/yaml"
	"github.com/spf13/viper"
)

func main() {
	expWrite()
	actWrite()

}

func expWrite() {
	configName := "config-exp"
	viper := viper.New()
	viper.Set("version", "3")
	viper.SetConfigName(configName)
	viper.AddConfigPath(".")

	viper.Set("kafka-server.image", "wurstmeister/kafka")
	viper.Set("kafka-server.environment.KAFKA_LISTENERS", "INSIDE://:9092,OUTSIDE://:29092")

	ymlStr, err := yamlStringSettings(viper)
	if err != nil {
		fmt.Printf("write to %v.yml error:%v\n", configName, err)
		return
	}
	ymlStr = strings.Replace(ymlStr, "kafka_listeners", "KAFKA_LISTENERS", -1)

	if writeFile(configName+".yml", ymlStr); err != nil {
		fmt.Printf("write to %v.yml error:%v", configName, err)
		return
	}
}

func actWrite() {
	viper.Set("version", "3")
	viper.SetConfigName("config-act")
	viper.AddConfigPath(".")

	viper.Set("kafka-server.image", "wurstmeister/kafka")
	viper.Set("kafka-server.environment.KAFKA_LISTENERS", "INSIDE://:9092,OUTSIDE://:29092")
	viper.WriteConfig()
}


func yamlStringSettings(vip *viper.Viper) (ymlString string, err error) {
	c := vip.AllSettings()
	bs, err := yaml.Marshal(c)
	if err != nil {
		return
	}
	ymlString = string(bs)
	return
}

func writeFile(fileName, content string) (err error) {
	out, err := os.OpenFile(fileName, os.O_WRONLY|os.O_TRUNC|os.O_CREATE, os.ModePerm)
	if err != nil {
		fmt.Println(err)
		return
	}
	_, err = out.WriteString(content)
	return
}
```

### information
>    https://github.com/wurstmeister/kafka-docker#listener-configuration
