### ISSUE TITLE
Allow default values on array of struct

### ISSUE THREAD

**Issue by dealancer** [spf13/viper#700]
Let's say I have a YAML like this

```
connections:
  - name: demo
    hosts:
      - "demo.example.com:9200"
    username: admin
    password: password
    ssl: true
    ssl_verify: true
    version: 7
  - name: test
    hosts:
      - "test.example.com:9200"
    username: admin
    password: password
```

And a struct like this

```
type Config struct {
    Connections []struct {
        Name      string
        Hosts     []string
        Username  string
        Password  string
        Ssl       bool
        SslVerify bool
        Version   int
    }
}
```

And I want following code to set a default value for `Config.Connections[*].Ssl` :

```
viper.SetDefault("connections[].ssl", "true")
```

Right now it is not happening, probably because `Config.Connections` is not initialized before the Unmarshalling.
