### ISSUE TITLE
Viper writes wrong config after Set()

### ISSUE THREAD

**Issue by pomo-mondreganto** [spf13/viper#717]
I have a simple nested YAML config like this: 

```
services:
  hipstore:
    port: 7878
    proto: tcp
  test_tcp:
    port: 1337
    proto: tcp
  test_udp:
    port: 1337
    proto: udp
```

After loading, I need to make some changes to config and write it back to file, so I do:

```
viper.Set("services", servicesConfig)
```

Where `servicesConfig` is a new config map without first service (`hipstore` in that case). 

After that, I print the value of `"services"` key for debugging and see the expected output: 

```
fmt.Println(viper.GetStringMap("services"))
```

results in 

```
map[test_tcp:map[port:1337 proto:tcp] test_udp:map[port:1337 proto:udp]]
```

But after writing config to a file (e.g. `test.yml`): 

```
viper.WriteConfigAs("test.yml")
```

In `test.yml` I see my old config, with `hipstore` service, so `WriteConfigAs` (as well as `WriteConfig`) somehow writes my old config after explicitly setting the key to a different value (in this case, deleting one of the map keys).
