### ISSUE TITLE
how can i toml block set/write?

### ISSUE THREAD

**Issue by halidaltuner** [spf13/viper#789]
I have a struct from client for changing TOML file. But viper.set and viper.write not running on block configs. Only field-by-field update is working.
example toml block:

```toml
[datetime]
  datetimeformat = "ddhhyy"
  ntpserver = true
  ntpserveraddress = "192.168.1.1"
  ntpserverport = 124
  timezone = "Europe/GMT+3"
```

struct based viper set
```go
viper.Set("datetime", datetimeObj)
viper.WriteConfig()
```

When this code runs, flush all configs from file.
