### ISSUE TITLE
Issues with overriding config using ENV variables in Viper

### ISSUE THREAD

**Issue by gurpreetkh** [spf13/viper#904]
Hi Team!

We are using Viper to read and parse our config file and all of that works without any issues. 

However we are not able to override some of our config values using env variables. These are specific use cases where the config is bound to a struct or an array of structs (which is our use case).

Here is an example from our config.yaml:
    ```
app:
        verifiers:
          - name: "test1"
            url: "http://test1.url"
            cache: "5000ms"
    	  - name: "test2"
    	    url: "http://test2.url"
    	    cache: "10000ms"
```

Which is bound to the following structs (golang):

  ```
  type App struct {
    	AppConfig   Config      `yaml:"app" mapstructure:"app"`
    }
    
    type Config struct {
    	Verifiers []VerifierConfig `json:"verifiers"         yaml:"verifiers"         mapstructure:"verifiers"`
    }
    
    type VerifierConfig struct {
    	Name     string            `json:"name"                   yaml:"name"                   mapstructure:"name"`
    	URL      string            `json:"url,omitempty"          yaml:"url,omitempty"          mapstructure:"url"`
    	cache    jsontime.Duration `json:"cache"                  yaml:"cache"                  mapstructure:"cache"`
    }
```

As we can see,  AuthConfig is bound to an array of structs.  We've tried a few different ways of overriding this config using env variables without any success. 

Here are the Viper options we have used:
    ```
viper.AutomaticEnv()
    viper.SetEnvKeyReplacer(strings.NewReplacer(".", "_"))
```
and we read the config into mapstructures.

Is it safe to assume that Viper does not support this at the moment and if that is the case, can we raise  a change request for it please.

If anyone has run into similar issues and can provide some pointers, they would be greatly appreciated. 

Thanks!

**Comment by mrexox** [comment]
If you change a bit your config structure, it will work for the defined names:
```yaml
app:
   verifiers:
      test1:
        url: "http://test1.url"
        cache: "5000ms"
      test2:
    	url: "http://test2.url"
    	cache: "10000ms"
```
Of course, you need to change config structure a little bit. But hardly makes a difference for Go.

Unfortunately, I don't know how to add test3 via ENV 😕
