### ISSUE TITLE
MergeInConfig deep merge fail

### ISSUE THREAD

**Issue by christiangda** [spf13/viper#910]
I'm trying to merge two config files and it doesn't work properly, it looks like it doesn't make a deep merge of elements.

After the merge prevails the second file's conf

Shorth explanation

Example conf 1:

```yaml
array:
  -  id: 1
     val: 1

```

Example conf 2:

```yaml
array:
  -  id: 2
     val: 2

```

expected result:

```yaml
array:
  -  id: 1
     val: 1
  -  id: 2
     val: 2
```
got result:

```yaml
array:
  -  id: 2
     val: 2
```

**My code:**

```go
package main

import (
	"fmt"
	"path/filepath"

	"github.com/spf13/viper"
)

func main() {
	fmt.Println("Merging conf")

	file1 := "./m1.yaml"
	file2 := "./m2.yml"

	viper.SetConfigName(filepath.Base(file1))
	viper.AddConfigPath(filepath.Dir(file1))
	viper.SetConfigType(filepath.Ext(file1)[1:])

	if err := viper.ReadInConfig(); err != nil {
		fmt.Errorf("Error reading config file, %s", err)
	}
	fmt.Printf("Conf before merge: %v\n", viper.AllSettings())

	viper.SetConfigName(filepath.Base(file2))
	viper.AddConfigPath(filepath.Dir(file2))
	viper.SetConfigType(filepath.Ext(file2)[1:])

	if err := viper.MergeInConfig(); err != nil {
		fmt.Errorf("Error merging config file, %s", err)
	}

	fmt.Printf("Conf after merge: %v\n", viper.AllSettings())

}
```

conf file 1

```yaml
MetricDataQueries:
    - Id: m1
      MetricStat:
        Metric:
          Namespace: AWS/EC2
          MetricName: CPUUtilization
          Dimensions:
            - Name: AutoScalingGroupName
              Value: my-asg-1
        Period: 300
        Stat: Average
```

conf file 2

```yaml
MetricDataQueries:
    - Id: m2
      MetricStat:
        Metric:
          Namespace: AWS/EC2
          MetricName: NetworkOut
          Dimensions:
            - Name: AutoScalingGroupName
              Value: my-asg-2
        Period: 300
        Stat: SampleCount
```

after run
```bash
go run main.go
Merging conf
Conf before merge: map[metricdataqueries:[map[Id:m1 MetricStat:map[Metric:map[Dimensions:[map[Name:AutoScalingGroupName Value:my-asg-1]] MetricName:CPUUtilization Namespace:AWS/EC2] Period:300 Stat:Average]]]]
Conf after merge: map[metricdataqueries:[map[Id:m2 MetricStat:map[Metric:map[Dimensions:[map[Name:AutoScalingGroupName Value:my-asg-2]] MetricName:NetworkOut Namespace:AWS/EC2] Period:300 Stat:SampleCount]]]]
```
