### ISSUE TITLE
Viper overwrites existing config file and sort keys

### ISSUE THREAD

**Issue by valter-silva-au** [spf13/viper#941]
Hi All,
I have a config file that looks like this:
```
Logo: 
  Label: Logo
  URL: https://via.placeholder.com/512x90.png

App:
  Name: Application Name
  ID: Application ID from your catalog
  Function:	Describe Application Function
  Owner: Name <name@email.com>
...
```

When I instantiate a new config with Viper, my config keys get sorted and my keys are lowercased:
```
app:
  name: Application Name
  id: Application ID from your catalog
  function:	Describe Application Function
  owner: Name <name@email.com>

logo: 
  label: Logo
  url: https://via.placeholder.com/512x90.png
```

This is how I'm creating the new Viper object:
```
func GetCSD() *viper.Viper {
	csd := viper.New()
	csd.AddConfigPath(".")

	csd.SetConfigName("csd")
	csd.SetConfigType("yaml")
	csd.SetConfigPermissions(os.ModePerm)

	err := csd.ReadInConfig() // Find and read the config file
	if err != nil {           // Handle errors reading the config file
		panic(fmt.Errorf("Fatal error config file: %s", err))
	}

	return csd
}

```
Is there a way to keep my original config, at least its order?

Thank you.
